/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EditDiv: typeof import('./src/components/edit-div.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElEdit: typeof import('./src/components/el-edit.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    NestedFrame: typeof import('./src/components/nested-frame.vue')['default']
    NestedItem: typeof import('./src/components/nested-item.vue')['default']
    RawDisplayer: typeof import('./src/components/infra/raw-displayer.vue')['default']
  }

  export interface ComponentCustomProperties {
    vPopover: typeof import('element-plus/es')['ElPopoverDirective']
  }
}
